-- =======================================================================================
-- 003_cotizaciones.sql
-- MIGRACIÓN PARA EL SISTEMA DE COTIZACIONES Y CHAT EN TIEMPO REAL
-- =======================================================================================

-- 1. Crear tabla de cotizaciones
CREATE TABLE IF NOT EXISTS public.cotizaciones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cliente_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre_cliente TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'en_progreso', 'finalizado')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Crear tabla de mensajes_chat
CREATE TABLE IF NOT EXISTS public.mensajes_chat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cotizacion_id UUID NOT NULL REFERENCES public.cotizaciones(id) ON DELETE CASCADE,
    enviado_por TEXT NOT NULL CHECK (enviado_por IN ('cliente', 'asistente_ai', 'admin')),
    mensaje TEXT NOT NULL,
    archivo_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Habilitar RLS en ambas tablas
ALTER TABLE public.cotizaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mensajes_chat ENABLE ROW LEVEL SECURITY;

-- 4. Políticas RLS para cotizaciones
-- Usuarios (autenticados o anónimos) pueden ver solo sus propias cotizaciones
CREATE POLICY "Usuarios ven sus propias cotizaciones"
    ON public.cotizaciones FOR SELECT
    USING (auth.uid() = cliente_id OR public.is_admin_or_superadmin(auth.uid()));

-- Usuarios (autenticados o anónimos) pueden crear sus propias cotizaciones
CREATE POLICY "Usuarios pueden crear sus propias cotizaciones"
    ON public.cotizaciones FOR INSERT
    WITH CHECK (auth.uid() = cliente_id);

-- Solo admins pueden actualizar cotizaciones (ej. cambiar estado)
CREATE POLICY "Admins pueden actualizar cotizaciones"
    ON public.cotizaciones FOR UPDATE
    USING (public.is_admin_or_superadmin(auth.uid()));

-- 5. Políticas RLS para mensajes_chat
-- Los usuarios pueden ver mensajes de sus propias cotizaciones
CREATE POLICY "Usuarios ven mensajes de sus cotizaciones"
    ON public.mensajes_chat FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.cotizaciones c 
            WHERE c.id = mensajes_chat.cotizacion_id 
            AND (c.cliente_id = auth.uid() OR public.is_admin_or_superadmin(auth.uid()))
        )
    );

-- Los usuarios pueden insertar mensajes en sus propias cotizaciones
CREATE POLICY "Usuarios pueden enviar mensajes a sus cotizaciones"
    ON public.mensajes_chat FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.cotizaciones c 
            WHERE c.id = mensajes_chat.cotizacion_id 
            AND (c.cliente_id = auth.uid() OR public.is_admin_or_superadmin(auth.uid()))
        )
    );

-- 6. Habilitar Realtime para la tabla mensajes_chat
-- Primero comprobamos si existe la publicación, si no la creamos (Supabase la crea por defecto)
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime;
COMMIT;
-- Añadir la tabla a la publicación
ALTER PUBLICATION supabase_realtime ADD TABLE public.mensajes_chat;


-- =======================================================================================
-- CONFIGURACIÓN DEL STORAGE
-- =======================================================================================

-- Crear el bucket si no existe
INSERT INTO storage.buckets (id, name, public)
VALUES ('documentos-cotizaciones', 'documentos-cotizaciones', true)
ON CONFLICT (id) DO NOTHING;

-- Políticas para el bucket 'documentos-cotizaciones'

-- Permitir a cualquier usuario ver archivos (útil si quieres mostrar el enlace en el chat)
CREATE POLICY "Cualquiera puede ver documentos"
ON storage.objects FOR SELECT
USING (bucket_id = 'documentos-cotizaciones');

-- Permitir a los usuarios subir archivos a su propia carpeta (la carpeta será su auth.uid())
CREATE POLICY "Usuarios pueden subir documentos a su carpeta"
ON storage.objects FOR INSERT
WITH CHECK (
    bucket_id = 'documentos-cotizaciones' 
    AND auth.role() = 'authenticated' -- Esto incluye a usuarios anónimos en Supabase
    AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Permitir a los admins gestionar cualquier archivo
CREATE POLICY "Admins pueden gestionar documentos"
ON storage.objects FOR ALL
USING (
    bucket_id = 'documentos-cotizaciones' 
    AND public.is_admin_or_superadmin(auth.uid())
);
