-- ═══════════════════════════════════════════════════════════════
-- Migración 008: Tabla alpha_notes
-- Descripción: Notas guardadas por A.L.P.H.A. (el asistente IA)
--              cuando el intent es 'save_note'.
-- Ejecutar en: Supabase Dashboard > SQL Editor
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.alpha_notes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  note_content TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.alpha_notes IS 'Notas guardadas automáticamente por A.L.P.H.A. vía tool_name=save_note';

-- Índices
CREATE INDEX IF NOT EXISTS idx_alpha_notes_user_id ON public.alpha_notes (user_id);
CREATE INDEX IF NOT EXISTS idx_alpha_notes_created_at ON public.alpha_notes (created_at DESC);

-- RLS
ALTER TABLE public.alpha_notes ENABLE ROW LEVEL SECURITY;

-- Cada usuario puede leer sus propias notas
CREATE POLICY "Usuarios ven sus propias notas"
  ON public.alpha_notes FOR SELECT
  USING (auth.uid() = user_id);

-- La inserción se hace desde la Edge Function con service_role_key,
-- por lo que no necesita política INSERT para el usuario normal.
-- Pero el admin puede leer todas.
CREATE POLICY "Admins leen todas las notas"
  ON public.alpha_notes FOR SELECT
  USING (public.is_admin_or_superadmin(auth.uid()));

-- Solo la Edge Function (service_role) inserta, pero por si acaso
-- permitir inserción al propietario
CREATE POLICY "Usuario puede insertar sus notas"
  ON public.alpha_notes FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Admin puede borrar notas
CREATE POLICY "Admin gestiona notas"
  ON public.alpha_notes FOR DELETE
  USING (public.is_admin_or_superadmin(auth.uid()));
