-- ═══════════════════════════════════════════════════════════════
-- Migración 009: Rate Limiting & user_logs Protection
-- Descripción: Limita peticiones del chatbot AI para prevenir costos
--              y protege user_logs contra spam de inserción.
-- Ejecutar en: Supabase Dashboard > SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- ─── 1. TABLA PARA CONTROL DE RATE LIMIT ───────────────────────
CREATE TABLE IF NOT EXISTS public.rate_limit_events (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip          TEXT,
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  action      TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.rate_limit_events IS 'Historial de solicitudes para control de rate-limit de Edge Functions';

-- Índices eficientes para búsquedas
CREATE INDEX IF NOT EXISTS idx_rate_limit_events_ip_action ON public.rate_limit_events (ip, action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_rate_limit_events_user_action ON public.rate_limit_events (user_id, action, created_at DESC);

-- Habilitar RLS (ningún usuario puede leer o escribir directamente)
ALTER TABLE public.rate_limit_events ENABLE ROW LEVEL SECURITY;

-- ─── 2. FUNCIÓN RPC PARA CHECK DE RATE LIMIT ───────────────────
CREATE OR REPLACE FUNCTION public.check_rate_limit(
  p_ip TEXT,
  p_user_id UUID,
  p_action TEXT,
  p_max_requests INT,
  p_window_minutes INT
)
RETURNS BOOLEAN AS $$
DECLARE
  v_count INT;
  v_bucket_start TIMESTAMPTZ;
BEGIN
  -- Limpieza probabilística del historial viejo (5% de probabilidad)
  IF random() < 0.05 THEN
    DELETE FROM public.rate_limit_events WHERE created_at < now() - INTERVAL '1 day';
  END IF;

  v_bucket_start := now() - (p_window_minutes || ' minutes')::INTERVAL;

  -- Contar peticiones en la ventana de tiempo
  IF p_user_id IS NOT NULL THEN
    SELECT COUNT(*) INTO v_count
    FROM public.rate_limit_events
    WHERE user_id = p_user_id
      AND action = p_action
      AND created_at >= v_bucket_start;
  ELSE
    SELECT COUNT(*) INTO v_count
    FROM public.rate_limit_events
    WHERE ip = p_ip
      AND action = p_action
      AND created_at >= v_bucket_start;
  END IF;

  -- Validar contra el límite especificado
  IF v_count >= p_max_requests THEN
    RETURN FALSE;
  END IF;

  -- Insertar el nuevo evento
  INSERT INTO public.rate_limit_events (ip, user_id, action)
  VALUES (p_ip, p_user_id, p_action);

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- ─── 3. TRIGGER DE RATE LIMIT Y SANITIZACIÓN PARA USER_LOGS ────
CREATE OR REPLACE FUNCTION public.rate_limit_user_logs()
RETURNS TRIGGER AS $$
DECLARE
  v_ip TEXT;
  v_count INT;
BEGIN
  -- 3.1 Sanitización de campos
  IF length(NEW.event) > 100 THEN
    NEW.event := substring(NEW.event from 1 for 100);
  END IF;
  
  IF NEW.metadata IS NOT NULL AND octet_length(NEW.metadata::text) > 10000 THEN
    RAISE EXCEPTION 'Payload de metadatos excede el límite de tamaño de 10KB.';
  END IF;

  IF NEW.user_agent IS NOT NULL AND length(NEW.user_agent) > 500 THEN
    NEW.user_agent := substring(NEW.user_agent from 1 for 500);
  END IF;

  -- 3.2 Obtener la IP real del servidor de Supabase
  BEGIN
    v_ip := split_part(current_setting('request.headers', true)::json->>'x-forwarded-for', ',', 1);
  EXCEPTION WHEN OTHERS THEN
    v_ip := NULL;
  END;

  -- Evitar spoofing sobrescribiendo el ip_hint de manera segura en backend
  NEW.ip_hint := COALESCE(v_ip, 'unknown');

  -- 3.3 Rate-Limit de inserción (máximo 60 logs por minuto por IP)
  IF NEW.ip_hint <> 'unknown' THEN
    SELECT COUNT(*) INTO v_count
    FROM public.user_logs
    WHERE created_at > now() - INTERVAL '1 minute'
      AND ip_hint = NEW.ip_hint;
      
    IF v_count >= 60 THEN
      RAISE EXCEPTION 'Límite de peticiones de logs excedido para esta dirección IP.';
    END IF;
  ELSE
    -- Rate limit global de contingencia para inserciones anónimas sin IP detectada (máximo 200 por minuto)
    SELECT COUNT(*) INTO v_count
    FROM public.user_logs
    WHERE created_at > now() - INTERVAL '1 minute'
      AND ip_hint = 'unknown';
      
    IF v_count >= 200 THEN
      RAISE EXCEPTION 'Límite de peticiones de logs globales excedido.';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Crear el trigger BEFORE INSERT
DROP TRIGGER IF EXISTS trg_rate_limit_user_logs ON public.user_logs;
CREATE TRIGGER trg_rate_limit_user_logs
  BEFORE INSERT ON public.user_logs
  FOR EACH ROW EXECUTE FUNCTION public.rate_limit_user_logs();
