-- ═══════════════════════════════════════════════════════════════
-- Migración 010: CMS de Secciones, Temas Dinámicos y Contenido
-- Descripción: Agrega soporte para orden dinámico, personalización de colores,
--              y tablas para proyectos y servicios editables desde el panel.
-- Ejecutar en: Supabase Dashboard > SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- ─── 1. TABLA: PROYECTOS ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.proyectos (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT NOT NULL,
  description TEXT NOT NULL,
  tags        TEXT[] DEFAULT '{}',
  url         TEXT,
  color       TEXT, -- Clases de gradiente de Tailwind (ej: 'from-tesseract-500/20 to-blue-500/20')
  accent      TEXT, -- Color de acento hex (ej: '#06b6d4')
  is_visible  BOOLEAN DEFAULT true,
  order_index INT DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.proyectos IS 'Proyectos personales editables en el portafolio';

-- Habilitar RLS
ALTER TABLE public.proyectos ENABLE ROW LEVEL SECURITY;

-- Políticas de Seguridad para Proyectos
CREATE POLICY "Lectura pública de proyectos"
  ON public.proyectos FOR SELECT
  USING (is_visible = true OR public.is_admin_or_superadmin(auth.uid()));

CREATE POLICY "Admin gestiona proyectos"
  ON public.proyectos FOR ALL
  USING (public.is_admin_or_superadmin(auth.uid()))
  WITH CHECK (public.is_admin_or_superadmin(auth.uid()));

-- Insertar datos semilla de proyectos (basados en siteData.js)
INSERT INTO public.proyectos (title, description, tags, url, color, accent, order_index)
VALUES 
(
  'Pablito Expo',
  'Editor interactivo de presentaciones con generación de contenido mediante Inteligencia Artificial (DeepSeek).',
  ARRAY['React', 'Canvas', 'IA'],
  'https://expo.sypablitodp.site',
  'from-tesseract-500/20 to-blue-500/20',
  '#06b6d4',
  1
),
(
  'Grafiplot',
  'Landing page premium y dashboard de administración para servicio de impresión digital.',
  ARRAY['Next.js', 'Supabase', 'Tailwind'],
  'https://grafiplotvasquez.lat',
  'from-emerald-500/20 to-teal-500/20',
  '#10b981',
  2
)
ON CONFLICT DO NOTHING;


-- ─── 2. TABLA: SERVICIOS ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.servicios (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT NOT NULL,
  description TEXT NOT NULL,
  is_visible  BOOLEAN DEFAULT true,
  order_index INT DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.servicios IS 'Servicios ofrecidos editables en el portafolio';

-- Habilitar RLS
ALTER TABLE public.servicios ENABLE ROW LEVEL SECURITY;

-- Políticas de Seguridad para Servicios
CREATE POLICY "Lectura pública de servicios"
  ON public.servicios FOR SELECT
  USING (is_visible = true OR public.is_admin_or_superadmin(auth.uid()));

CREATE POLICY "Admin gestiona servicios"
  ON public.servicios FOR ALL
  USING (public.is_admin_or_superadmin(auth.uid()))
  WITH CHECK (public.is_admin_or_superadmin(auth.uid()));

-- Insertar datos semilla de servicios (basados en siteData.js)
INSERT INTO public.servicios (title, description, order_index)
VALUES 
(
  'Formateo APA 7ma Edición',
  'Ajuste riguroso de presentaciones, tesis y documentos bajo la normativa APA actual.',
  1
),
(
  'Creación de Monografías',
  'Redacción y estructura profesional de monografías para nivel secundario y preuniversitario.',
  2
),
(
  'Material Gráfico',
  'Diseño de trípticos, dípticos y material publicitario escolar o de negocios.',
  3
),
(
  'Curriculum Vitae (CV)',
  'Diseño y redacción de CVs de alto impacto, modernos y optimizados para entrevistas.',
  4
)
ON CONFLICT DO NOTHING;


-- ─── 3. COLUMNAS DE CONFIGURACIÓN EN SITE_CONFIG ───────────────
ALTER TABLE public.site_config
ADD COLUMN IF NOT EXISTS section_order JSONB NOT NULL DEFAULT '["expediente", "modules", "arsenal", "proyectos", "servicios", "contacto"]'::jsonb,
ADD COLUMN IF NOT EXISTS theme JSONB NOT NULL DEFAULT '{
  "mode": "dark",
  "bg_color": "#030712",
  "card_color": "#0a0f25",
  "accent_color": "#06b6d4",
  "glow_color": "rgba(6, 182, 212, 0.15)",
  "particles": true
}'::jsonb;

-- Actualizar la fila única existente
UPDATE public.site_config
SET 
  section_order = COALESCE(section_order, '["expediente", "modules", "arsenal", "proyectos", "servicios", "contacto"]'::jsonb),
  theme = COALESCE(theme, '{
    "mode": "dark",
    "bg_color": "#030712",
    "card_color": "#0a0f25",
    "accent_color": "#06b6d4",
    "glow_color": "rgba(6, 182, 212, 0.15)",
    "particles": true
  }'::jsonb)
WHERE id = 'main';
